FROM java:openjdk-8-alpine

ENV ANDROID_HOME /opt/android-sdk-linux
ENV PATH ${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

COPY install.sh install.sh

RUN apk update && apk add bash tar libstdc++ && chmod +x install.sh && ./install.sh && rm install.sh && rm /var/cache/apk/*